# Based on https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
name: Code Style

# trigger on PRs and main branches
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint
        run: |
          uv run ruff check --output-format=github
